apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: typesense-operator
  name: typesense-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typesense-operator
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: typesense-operator
    spec:
      serviceAccountName: typesense-operator-sa
      containers:
      - name: typesense-operator
        image: sai3010/typesense-operator:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"